---

- name: Assertions
  ansible.builtin.assert:
    that:
      - postgresql_database is defined
      - postgresql_username is defined
      - postgresql_password is defined

- name: Create Docker compose directory
  ansible.builtin.file:
    path: "{{ postgresql_compose_dir }}"
    state: directory
    owner: root
    group: "{{ 'docker' if 'docker' in ansible_local['groups'] else 'root' }}"
    mode: "0750"

- name: Create Postgres data directory
  ansible.builtin.file:
    path: "{{ postgresql_data_dir }}"
    state: directory
    owner: 999
    group: 999
    mode: "0775"

- name: Template Docker compose config
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ postgresql_compose_dir }}/docker-compose.yml"
    owner: root
    group: "{{ 'docker' if 'docker' in ansible_local['groups'] else 'root' }}"
    mode: "0600"

- name: Start Postgres container
  community.docker.docker_compose:
    project_name: "postgres"
    project_src: "{{ postgresql_compose_dir }}/"
